### ISSUE TITLE
'parent taxon' and 'ONTIE domain' have the same definition

### ISSUE THREAD

**Issue by beckyjackson** [IEDB/ONTIE#10]
https://github.com/IEDB/ONTIE/blob/a41fde961c3927aa0ae520e3b19d3b9ff7205d02/ontology/ontie.kn#L21073-L21082

It seems like 'ONTIE domain' should have a different defintion?

**Comment by jamesaoverton** [comment]
Yeah. The ONTIE domain is for internal use for sorting terms. See usage `templates.kn`. Please change the definition to: "An annotation property for the scientific domain of a term."

**Comment by beckyjackson** [comment]
Resolved by #12
