### ISSUE TITLE
Convert to ROBOT templates

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/ONTIE#18]
At this point I think we should abandon the dream of using Knotation for this and switch to ROBOT templates and a Google Sheet.

**Comment by beckyjackson** [comment]
I started a Google sheet here to contain all the templates - https://docs.google.com/spreadsheets/d/1DFij_uxMH74KR8bM-wjJYa9qITJ81MvFIKUSpZRPelw

I think I covered all the ONTIE domains, but let me know if you see anything missing (I haven't filled them in yet).

**Comment by jamesaoverton** [comment]
Yes, this looks great.
