### ISSUE TITLE
download ontie

### ISSUE THREAD

**Issue by rvita** [IEDB/ONTIE#22]
On OBI call, Mark asked for help downloading IEDB + ONTIE in a usable format.

**Comment by jamesaoverton** [comment]
I just merged #20, so now we have a proper [`ontie.owl`](https://github.com/IEDB/ONTIE/blob/master/ontie.owl).

@turbomam does that cover your use case?

**Comment by turbomam** [comment]
Thanks. Will check later this afternoon.

**Comment by turbomam** [comment]
Thanks. I have downloaded https://github.com/IEDB/ONTIE/blob/master/ontie.owl

What else is there RDF/OWL-wise in the IEDB universe? Where would I find axioms about the relationships (disposition to bind, etc.) between antigens and antibodies?

**Comment by jamesaoverton** [comment]
We've built multiple prototypes over the years to convert IEDB data to RDF/OWL, for a few different use cases. But I can't think of anything that quite fits what you're asking for.

**Comment by eipikun** [comment]
[https://github.com/IEDB/ONTIE/blob/master/ontie.owl](https://github.com/IEDB/ONTIE/blob/master/ontie.owl) is the content what I was able to expect to be seen at [https://ontology.iebd.org/ontology/ontie.owl](https://ontology.iebd.org/ontology/ontie.owl) which is on [documentation](https://ontology.iedb.org/ontology)?

**Comment by jamesaoverton** [comment]
@eipikun The ontology.iedb.org site was slightly behind this repository, but I have just updated it, so they should now be in sync. Does that answer your question?

**Comment by eipikun** [comment]
@jamesaoverton Yes, it does. Thank you for checking the difference and I understood the point. I checked updated one and I'm sorry for my late reply.

**Comment by turbomam** [comment]
By the way, I don't "need" anything from this issue any more. Thanks.

**Comment by jamesaoverton** [comment]
Ok, thanks everybody.
