### ISSUE TITLE
New terms for CMI-PB

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/ONTIE#28]
I need the following terms for the CMI-PB project. I'd like to reserve these IDs and use them right away:

ID | Label | Parent
---|---|---
ONTIE:0003550 | Pertussis toxin complex | GO protein complex
ONTIE:0003551 | Pertussis toxin complex, inactivated by PFA | Pertussis toxin complex
ONTIE:0003552 | Pertussis toxin complex, inactivated mutant | Pertussis toxin complex
ONTIE:0003553 | mixture of Fim2 and Fim3 | ChEBI mixture?

It's worthwhile creating a protein-complex template to handle the first three. I guess it makes sense for the fourth to also go on that sheet, even though it's a mixture and not actually a complex.

We have a list of parts for 'Pertussis toxin complex' and 'mixture of Fim2 and Fim3' but they're UniProt IDs. Please check if they're in PR.

Uniprot | Label | Synonym
-- | -- | --
P04977 | Pertussis toxin subunit 1
P04978 | Pertussis toxin subunit 2
P04979 | Pertussis toxin subunit 3
P0A3R5 | Pertussis toxin subunit 4
P04981 | Pertussis toxin subunit 5
Q5I8X0 | Fimbrial protein | Fim2
A0A171JW18 | Fimbrial protein Fim3 | Fim3

**Comment by beckyjackson** [comment]
If those are in PR, should I import them?

**Comment by jamesaoverton** [comment]
Yes please. If any of them are not in PR, please just include the Uniprot IDs as an `rdfs:comment` for now.
