### ISSUE TITLE
Add MGI IDs as xrefs

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/ONTIE#3]

**Comment by beckyjackson** [comment]
Should this use the `oboInOwl:hasDbXref` property?

**Comment by jamesaoverton** [comment]
I think so, but I don't have much experience with that property. How do other projects use it?

**Comment by beckyjackson** [comment]
DO uses it in a similar way - to reference other database entries that are the same thing, such as in OMIM. It's also used as an annotation on definitions to show the source.

**Comment by beckyjackson** [comment]
I think this is resolved by #6 - should we close it?
