### ISSUE TITLE
Tabs of diff table should be bold if there are differences

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/ONTIE#39]
I like the diff table a lot. It would be better if the tabs with differences were distinct from the tabs with no differences. And it would be even better if the default tab was the first tab with changes.

**Comment by beckyjackson** [comment]
Why not just display only the pages with differences? I don't think there's any reason to look at the non-diff tables because they have no data anyway.

**Comment by jamesaoverton** [comment]
Good point. My worry is that the user will think that we didn't check those tables, but maybe you're right.
