### ISSUE TITLE
New CoVIC terms

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/ONTIE#49]
*Work in progress*. I'll update the issue when I'm done.

I'm using these IDs for new ONTIE terms:

1. Parameters

ID | Label
-- | --
ONTIE:0003576 | Starting dilution fold
ONTIE:0003577 | Starting concentration (ug/mL)
ONTIE:0003578 | 4-PL curve parameter A
ONTIE:0003579 | 4-PL curve parameter B
ONTIE:0003580 | 4-PL curve parameter C
ONTIE:0003581 | 4-PL curve parameter D
ONTIE:0003582 | 4-PL curve R2

2. Assays

ID | Label
-- | --
ONTIE:0003583 | inflammation
ONTIE:0003584 | edema
ONTIE:0003585 | vasculitis
ONTIE:0003586 | necrosis
ONTIE:0003587 | hemorrhage
ONTIE:0003588 | weight
ONTIE:0003589 | viral titer nasal turbinates
ONTIE:0003590 | viral titer lung

3. Death status

ID | Label
-- | --
ONTIE:0003591 | ethical euthanization
ONTIE:0003592 | euthanized as planned
ONTIE:0003593 | unplanned death
ONTIE:0003594 | survived until end

4. Animal model strain

ID | Label
-- | --
ONTIE:0003595 | K18 hACE2 transgenic mouse

5. Antibody controls

ID | Label
-- | --
ONTIE:0003596 | isotype control
ONTIE:0003597 | mock-treated PBS-control
ONTIE:0003598 | PBS
ONTIE:0003599 | KZ52
ONTIE:0003600 | CR3022
ONTIE:0003601 | Convalescent Plasma 1
ONTIE:0003602 | Convalescent Plasma 2
ONTIE:0003603 | Negative Plasma

6. More assays

ID | Label
---|---
ONTIE:0003609 | neutralization IC50 (ng/mL)
ONTIE:0003610 | neutralization IC80 (ng/mL)

7. More parameters

ID | Label
---|---
ONTIE:0003611 | ULOD (ng/mL)
ONTIE:0003612 | LLOD (ng/mL)
ONTIE:0003613 | MPI (%)

8. More controls

ID | Label
---|---
ONTIE:0003614 | untreated uninfected control

**Comment by jamesaoverton** [comment]
@beckyjackson Can you please try to add these using the definitions in [this Google Sheet](https://docs.google.com/spreadsheets/d/11ItLLoXY7_r2lDazY4prMERHMb-7czrim91UABnvbYM/edit#gid=844590069)?

**Comment by beckyjackson** [comment]
For placement in templates:
* Parameters -> other?
* Assays -> assays
* Death status -> other (what is/are the parent(s) for these terms?)
* Animal model strain -> taxon
* Antibody controls -> other?

This seems like a lot to go in "other"... we could make "parameter" and "control" templates, but maybe this is the only time they would be used?

**Comment by beckyjackson** [comment]
Also, those assays don't look like assays, so now I'm a bit confused. Maybe more accurate under "host health status"?

**Comment by jamesaoverton** [comment]
"Other" is fine. It's true that these labels for the assays don't sound like assays, but the definitions should make it clear: "in vivo protection assay based on inflammation score of 0-5". We can clean these up later. I would just like to get the IDs in the right places and not just on this stupid issue I created. Thanks!

**Comment by beckyjackson** [comment]
Got it! And the "death status" terms have no parent, is that OK for now?

**Comment by jamesaoverton** [comment]
Actually, please give those four "death status" terms a new "death status" term as a parent.
