### ISSUE TITLE
More new terms for CoVIC-DB

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/ONTIE#59]
[Edited]

ID | Label | Definiton | Parent
---|---|---|---
ONTIE:0003635 | neutralization IC90 (ng/mL) | a neutralization assay measuring the IC90 of the tested antibody in ng/mL | assay
ONTIE:0003636 | R^2adj | adjusted R-squared | parameter

**Comment by beckyjackson** [comment]
These IDs are already taken by the new predicates we added for IEDB, can these be ONTIE:0003635 and ONTIE:0003636?

**Comment by jamesaoverton** [comment]
Yes, I'll change them. Sorry!

**Comment by beckyjackson** [comment]
@hectorguzor can you please try using DROID (https://droid.ontodev.com/ONTIE) to make a new branch and PR with these two new terms? No rush, only if you run out of other things to do 🙂

**Comment by jamesaoverton** [comment]
Closed by #62
